sonar.projectKey=jeobran69367_abassurance-merger
sonar.organization=jeobran69367
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.exclusions=data/**,src/ml/artifacts/**