sonar.projectKey=abassurance-merger
sonar.organization=<a-completer-avec-ton-org-sonarcloud>
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.exclusions=data/**,src/ml/artifacts/**
